#!/bin/bash
# setup_cases_v6.sh — E30: link the v5-era particle files (.obj) of ~/run/vulkan-demo/cases into
# the v6 checkout's case directories, one file at a time. The case.yaml stays the real file from
# the deployed commit (current numerics; a linked yaml or directory would load the v5 checkout's
# old yaml and materials, and any edit through it would change the v5 checkout).
# cavity3d_*_b4 directories on N56 hold only a yaml; their particles are the same border-4 sets
# generated by gen_3d_families.sh without the suffix (identical counts and pool size).
set -u
DEST=${DEST:-$HOME/run/vulkan-demo-v6}
SOURCE=$HOME/run/vulkan-demo/cases
MAP="lid_driven_cavity_2d_n1000:lid_driven_cavity_2d lid_driven_cavity_2d_16m:lid_driven_cavity_2d_16m
lid_driven_cavity_2d_64m:lid_driven_cavity_2d_64m lid_driven_cavity_2d_128m:lid_driven_cavity_2d_128m
cavity3d_weak4_k2_8m_b4:cavity3d_weak4_k2_8m cavity3d_weak8_k8_64m_b4:cavity3d_weak8_k8_64m"
for pair in $MAP; do
    target=${pair%%:*}; origin=${pair##*:}
    [ -f "$DEST/cases/$target/case.yaml" ] && [ ! -L "$DEST/cases/$target/case.yaml" ] \
        || { echo "ABORT: $target has no real case.yaml"; exit 2; }
    for name in frame domain wall wall_top; do
        [ -f "$SOURCE/$origin/$name.obj" ] || { echo "ABORT: missing $SOURCE/$origin/$name.obj"; exit 2; }
        ln -sfn "$SOURCE/$origin/$name.obj" "$DEST/cases/$target/$name.obj"
    done
    echo "$target <- $origin: $(ls -lL "$DEST/cases/$target/domain.obj" | awk '{print $5}') B domain.obj"
done
# the 1M particle set must be the generator set the E6b gates used (lid_driven_cavity_2d_gen = n1000 yaml)
echo "1M domain.obj sha256 $(sha256sum "$SOURCE/lid_driven_cavity_2d/domain.obj" | cut -d' ' -f1)" \
     "(expected ddeddf4035e2ffde6e26a52445e707e660ee2e8d4734206f25718ff33b5ba08d)"
