"""
_demo_cavity_case_3d.py — build a 3D lid-driven-cavity case from the tool.

3D analog of _demo_cavity_case.py: fluid cube [-0.5,0.5]^3 (1 m) on a simple-
cubic lattice, surrounded by a BORDER-thick shell on all six faces; the band
directly ABOVE the fluid footprint is the moving lid (stick_lid, +x), the rest
of the shell is static wall. Emits frame.obj / domain.obj / wall.obj /
wall_top.obj / case.yaml + a 3-slice preview.

3D-specific choices (see memory/project-v5-3d-readiness.md):
  - h/dx = 4 (not the 2D case's 5): neighbor count ~(4π/3)(h/dx)^3 is the
    dominant 3D cost knob — 268 at 4 vs 523 at 5.
  - max_per_voxel = 128 ≥ closest-packing bound ceil(√2·(h/dx)^3) = 91.
    The V5 loader does NOT self-check this; an undersized cap fails silently
    as particle kills.
  - max_incoming = 32 (a 3D voxel has 26 inflow neighbors vs 8 in 2D).

    .venv/Scripts/python.exe utils/geometry/_demo_cavity_case_3d.py --half 50  --out cases/cavity3d_1m   # 101^3 ≈ 1.03M fluid
    .venv/Scripts/python.exe utils/geometry/_demo_cavity_case_3d.py --half 100 --out cases/cavity3d_8m   # 201^3 ≈ 8.12M fluid
"""

from __future__ import annotations

import argparse
import math
import pathlib
import sys

import numpy as np

_REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

FLUID_HALF_EXTENT = 0.5            # fluid cube [-0.5, 0.5]^3 = 1 m cavity


def write_obj(path, points_3d):
    np.savetxt(path, points_3d, fmt="v %.6f %.6f %.6f",
               header=f"# {points_3d.shape[0]} particles", comments="")


def write_frame_obj(path, half_extent):
    h = half_extent
    vertices = np.array([
        [-h, -h, -h], [-h, h, -h], [h, -h, -h], [h, h, -h],
        [-h, -h,  h], [-h, h,  h], [h, -h,  h], [h, h,  h]])
    faces = [(1, 2, 4), (1, 4, 3), (5, 7, 8), (5, 8, 6), (1, 5, 6), (1, 6, 2),
             (3, 4, 8), (3, 8, 7), (1, 3, 7), (1, 7, 5), (2, 6, 8), (2, 8, 4)]
    with open(path, "w") as handle:
        handle.write("# cavity3d frame bbox\n")
        for vertex in vertices:
            handle.write(f"v {vertex[0]:.6f} {vertex[1]:.6f} {vertex[2]:.6f}\n")
        for face in faces:
            handle.write(f"f {face[0]} {face[1]} {face[2]}\n")


def write_preview(path, domain, wall, lid, dx):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    figure, axes = plt.subplots(1, 3, figsize=(18, 6))

    def slice_scatter(axis, clouds, slice_axis, keep_x, keep_y, title):
        window = 1.5 * dx
        for cloud, color, size in clouds:
            mask = np.abs(cloud[:, slice_axis]) < window
            axis.scatter(cloud[mask, keep_x], cloud[mask, keep_y], s=size, c=color)
        axis.set_title(title)
        axis.set_aspect("equal")

    clouds = [(domain, "tab:blue", 0.2), (wall, "tab:green", 0.2), (lid, "tab:red", 0.2)]
    slice_scatter(axes[0], clouds, 2, 0, 1, "z≈0 slice (x-y): lid on top")
    slice_scatter(axes[1], clouds, 1, 0, 2, "y≈0 slice (x-z): walls all around")
    zoom_window = 15 * dx

    axis = axes[2]
    for cloud, color, _ in clouds:
        mask = ((np.abs(cloud[:, 2]) < 1.5 * dx)
                & (np.abs(cloud[:, 0] + FLUID_HALF_EXTENT) < zoom_window)
                & (np.abs(cloud[:, 1] - FLUID_HALF_EXTENT) < zoom_window))
        axis.scatter(cloud[mask, 0], cloud[mask, 1], s=10, c=color)
    axis.set_title("top-LEFT corner zoom @ z≈0 (wall meets lid)")
    axis.set_aspect("equal")
    figure.tight_layout()
    figure.savefig(path, dpi=105)
    plt.close(figure)


CASE_YAML = """\
schema_version: 2

# 3D lid-driven cavity — {fluid_millions:.2f}M-particle case.
# GENERATED by utils/geometry/_demo_cavity_case_3d.py:
#   frame    = bounding box of the 1 m^3 cavity + border shell
#   domain   = {n_fluid:,} fluid particles (simple-cubic lattice)
#   wall     = {n_wall:,} static shell particles ({border} layers, 5 faces + edges)
#   wall_top = {n_lid:,} lid particles (band above the fluid footprint);
#              stick_lid has initial_velocity=[1,0,0]
# h = {h:.6f}, dx = {dx:.6f} -> h/dx = {hdx} (3D cost knob; 2D cases use 5).
# max_per_voxel {max_per_voxel} >= ceil(sqrt(2)*(h/dx)^3) = {packing_bound}
# (V5 loader does not self-check; undersized cap = SILENT particle kills).

time:
  total: null
  max_steps: null
  output_cadence: null

physics:
  dimension: 3
  h: {h:.6f}
  particle_radius: {particle_radius:.6f}
  lattice: grid
  calibrate_volume: true
  speed_of_sound: 100.0
  power: 7
  cfl: 0.15
  gravity: [0.0, 0.0, 0.0]

numerics:
  use_density_diffusion: true
  delta_coefficient: 0.1
  use_kcg_correction: true
  regularization:
    xi: 0.1
    det_threshold: 1.0e-4
    frobenius_max: 10.0
  use_pst: true
  pst_main: 0.1
  pst_anti: 0.0005
  defrag_enabled: true
  defrag_cadence: 1000
  use_prefix_sum_defrag: false

capacities:
  pool_size: {pool_size}
  max_per_voxel: {max_per_voxel}
  max_incoming: {max_incoming}
  workgroup: 128

material_library: ../../materials/standard.yaml

geometry:
  frame: frame.obj
  particles:
    - {{file: domain.obj,   material: stick_water}}
    - {{file: wall.obj,     material: stick_wall}}
    - {{file: wall_top.obj, material: stick_lid}}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--half", type=int, default=50,
                        help="fluid half-resolution: 0.5/dx (fluid is (2*half+1)^3 "
                             "particles). 50 -> ~1.03M, 100 -> ~8.12M, 116 -> ~12.6M")
    parser.add_argument("--hdx", type=int, default=4,
                        help="h/dx ratio (support radius in lattice units). 4 is the "
                             "3D default (268 neighbors); 5 matches the 2D cases but "
                             "costs ~2x (523 neighbors) and needs max_per_voxel >= 177.")
    parser.add_argument("--border", type=int, default=None,
                        help="wall shell layers (default 2*hdx+1)")
    parser.add_argument("--max-per-voxel", type=int, default=128)
    parser.add_argument("--max-incoming", type=int, default=32)
    parser.add_argument("--out", default="cases/cavity3d_1m")
    parser.add_argument("--no-preview", action="store_true")
    args = parser.parse_args()

    half_index = args.half
    dx = FLUID_HALF_EXTENT / half_index
    particle_radius = 0.5 * dx
    smoothing_length = args.hdx * dx
    border = args.border if args.border is not None else 2 * args.hdx + 1

    packing_bound = math.ceil(math.sqrt(2.0) * args.hdx ** 3)
    if args.max_per_voxel < packing_bound:
        print(f"ERROR: max_per_voxel={args.max_per_voxel} < closest-packing bound "
              f"{packing_bound} for h/dx={args.hdx}; the loader will NOT catch this "
              f"and particles will be killed silently.", file=sys.stderr)
        return 1

    half_total = half_index + border
    index = np.arange(-half_total, half_total + 1, dtype=np.int32)
    index_x, index_y, index_z = np.meshgrid(index, index, index, indexing="ij")
    index_x = index_x.ravel()
    index_y = index_y.ravel()
    index_z = index_z.ravel()

    in_fluid = ((np.abs(index_x) <= half_index)
                & (np.abs(index_y) <= half_index)
                & (np.abs(index_z) <= half_index))
    is_lid = ((index_y > half_index)
              & (np.abs(index_x) <= half_index)
              & (np.abs(index_z) <= half_index))
    is_wall = (~in_fluid) & (~is_lid)

    sites = np.column_stack([index_x * dx, index_y * dx, index_z * dx]).astype(np.float64)
    domain = sites[in_fluid]
    lid_points = sites[is_lid]
    wall = sites[is_wall]
    n_fluid, n_wall, n_lid = domain.shape[0], wall.shape[0], lid_points.shape[0]
    total = n_fluid + n_wall + n_lid
    pool_size = int(math.ceil(total * 1.15 / 128) * 128)

    out_dir = _REPO_ROOT / args.out
    out_dir.mkdir(parents=True, exist_ok=True)
    print(f"dx={dx:.6e}  h={smoothing_length:.6e}  h/dx={args.hdx}  border={border}")
    print(f"domain(fluid)={n_fluid:,}  wall={n_wall:,}  wall_top(lid)={n_lid:,}  total={total:,}")
    print(f"pool_size={pool_size:,}  max_per_voxel={args.max_per_voxel} "
          f"(bound {packing_bound})  max_incoming={args.max_incoming}")
    print(f"-> {out_dir}")

    write_obj(out_dir / "domain.obj", domain)
    write_obj(out_dir / "wall.obj", wall)
    write_obj(out_dir / "wall_top.obj", lid_points)
    frame_half = half_total * dx + 0.6 * dx
    write_frame_obj(out_dir / "frame.obj", frame_half)
    (out_dir / "case.yaml").write_text(CASE_YAML.format(
        fluid_millions=n_fluid / 1e6, n_fluid=n_fluid, n_wall=n_wall, n_lid=n_lid,
        border=border, h=smoothing_length, dx=dx, hdx=args.hdx,
        particle_radius=particle_radius, pool_size=pool_size,
        max_per_voxel=args.max_per_voxel, max_incoming=args.max_incoming,
        packing_bound=packing_bound), encoding="utf-8")
    print("wrote frame.obj domain.obj wall.obj wall_top.obj case.yaml")
    if not args.no_preview:
        write_preview(out_dir / "split_preview.png", domain, wall, lid_points, dx)
        print("wrote split_preview.png")
    return 0


if __name__ == "__main__":
    sys.exit(main())
